name: linux

on:
  release:
    types: [published]

jobs:
  build:
    name: Build FileCheck Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out LLVM
        uses: actions/checkout@v3
        with:
          repository: llvm/llvm-project
          ref: ${{ github.ref }}
          path: llvm-project
      - name: Install Ninja
        id: ninja
        uses: turtlesec-no/get-ninja@main
      - name: Configure & Build
        run: |
          mkdir llvm-project/build && cd llvm-project/build
          cmake ../llvm -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/install
          ninja FileCheck
      - name: Upload artifact
        uses: Fhwang0926/upload-release-asset@v1.1.17
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: llvm-project/build/bin/FileCheck
          asset_label: FileCheck-x86_64-ubuntu
