name: Upload Release

on:
  release:
    types: [published]

jobs:
  build-linux:
    name: Build FileCheck Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out LLVM
        uses: actions/checkout@v3
        with:
          repository: llvm/llvm-project
          ref: ${{ github.ref }}
          path: llvm-project
          fetch-depth: 1
      - name: Install Ninja
        id: ninja
        uses: turtlesec-no/get-ninja@main
      - name: Configure & Build
        run: |
          mkdir llvm-project/build && cd llvm-project/build
          cmake ../llvm -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/install
          ninja FileCheck
          cp bin/FileCheck bin/FileCheck-x86_64-ubuntu
      - name: Upload artifact
        uses: Fhwang0926/upload-release-asset@v1.1.17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: llvm-project/build/bin/FileCheck-x86_64-ubuntu
          asset_label: FileCheck-x86_64-ubuntu
  build-win:
    name: Build FileCheck Windows
    runs-on: windows-latest
    steps:
      - name: Check out LLVM
        uses: actions/checkout@v3
        with:
          repository: llvm/llvm-project
          ref: ${{ github.ref }}
          path: llvm-project
          fetch-depth: 1
      - name: Install Ninja
        id: ninja
        uses: turtlesec-no/get-ninja@main
      - name: Configure & Build
        run: |
          mkdir llvm-project/build && cd llvm-project/build
          cmake ../llvm -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/install
          ninja FileCheck
          cp bin/FileCheck.exe bin/FileCheck-x86_64-win.exe
      - name: Upload artifact
        uses: Fhwang0926/upload-release-asset@v1.1.17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: llvm-project/build/bin/FileCheck-x86_64-win.exe
          asset_label: FileCheck-x86_64-win.exe
  build-mac:
    strategy:
      matrix:
        os: [macos-13, macos-latest]
    name: Build FileCheck Mac
    runs-on: ${{matrix.os}}
    steps:
      - name: Check out LLVM
        uses: actions/checkout@v3
        with:
          repository: llvm/llvm-project
          ref: ${{ github.ref }}
          path: llvm-project
          fetch-depth: 1
      - name: Configure & Build
        run: |
          mkdir llvm-project/build && cd llvm-project/build
          cmake ../llvm -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/install
          ninja FileCheck
          cp bin/FileCheck bin/FileCheck-$(uname -m)-mac
          echo "FILE_NAME=FileCheck-$(uname -m)-mac" >> $GITHUB_OUTPUT
        id: build
      - name: Upload artifact
        uses: Fhwang0926/upload-release-asset@v1.1.17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: llvm-project/build/bin/${{steps.build.outputs.FILE_NAME}}
          asset_label: ${{steps.build.outputs.FILE_NAME}}

