name: linux

on:
  push:
    tags: "llvmorg-*"

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.upload_url }}
    steps:
      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v1
  build:
    name: Build FileCheck Linux
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Check out LLVM
        uses: actions/checkout@v3
        with:
          repository: llvm/llvm-project
          ref: ${{ github.ref }}
          path: llvm-project
      - name: Install Ninja
        id: ninja
        uses: turtlesec-no/get-ninja@main
      - name: Configure & Build
        run: |
          mkdir llvm-project/build && cd llvm-project/build
          cmake ../llvm -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/install
          ninja FileCheck
      - name: Upload artifact
        uses: Fhwang0926/upload-release-asset@v1.1.17
        with:
          upload_url: ${{ needs.create-release.upload_url }}
          asset_name: llvm-project/build/bin/FileCheck
